services:
  - docker

cache:
  directories:
    - docker-cache

before_script:
  - |
    filename=docker-cache/saved_images.tar
    if [[ -f "$filename" ]]; then docker load < "$filename"; fi
    mkdir -p docker-cache
    docker pull bitriseio/docker-android
    docker save -o "$filename" bitriseio/docker-android

script:
 - docker run bitriseio/docker-android
