language: java

services:
  - docker

before_install:
- docker pull bitriseio/docker-android
- docker run -it --rm --privileged -v /dev/bus/usb:/dev/bus/usb -v $PWD:/bitrise/src bitriseio/docker-android:latest cordova build
